### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by migbash** [Betarena/scores#1217]
`500 Internal Error`

> `[...]/player/davit-manoyan/49961` - NaN teams, check with Sportmonks and implement a solution to such cases.

---

<details close>
<summary>1. 🟩 Old `FIXTURES` exist on `API` endpoint</summary>
<br>

> ℹ Some upcoming `FIXTURES` show data from `FIXTURES` that where postponed and not removed from the list:

<img
src="https://github.com/Betarena/scores/assets/20924663/44038831-ad51-4f05-a1fe-72ebae8ed721"
width=150
/>

</details>

---

<details close>
<summary>2. 🟩 TEAMS have no `season_id`</summary>
<br>

> ℹ Some TEAMS have no `season_id`

<img
src="https://github.com/Betarena/scores/assets/20924663/80f23e65-d259-4d74-87d3-c1b16ef7609d"
width=150
/>

</details>

---

<details close>
<summary>3. 🟠 `CACHE` | Missing check for empty `player_data_updates` table</summary>
<br>

> When the `cache` fetches data from an `empty` DB - errors occur, need a `check`.

```
🐞 Issue Details

Job Id:

559

Worker:

CQ_PlayerStatistics

Log:

REDIS CACHE | player statistics

Finished on:

Tue, 06 Jun 2023 16:40:09 GMT

Job Data:

{ "dev": false, "cache_target_tag": "CQ_PlayerStatistics", "cache_target_log": "REDIS CACHE | player statistics", "del_cache": false, "tran_only": false }

Reason:

Cannot read properties of undefined (reading 'entries')

Stacktrace:

TypeError: Cannot read properties of undefined (reading 'entries') at mainData (file:///app/dist/bull/players/bull.statistics.js:64:34) at runMicrotasks () at processTicksAndRejections (node:internal/process/task_queues:96:5) at async mainPlayerStatisticsInit (file:///app/dist/bull/players/bull.statistics.js:51:5) at async Worker.connection [as processFn] (file:///app/dist/lib/bull/config.js:51:9) at async Worker.processJob (/app/node_modules/bullmq/dist/cjs/classes/worker.js:351:28) at async Worker.retryIfFailed (/app/node_modules/bullmq/dist/cjs/classes/worker.js:473:24) at async Worker.run (/app/node_modules/bullmq/dist/cjs/classes/worker.js:148:46)
```

> `NOTE` | Does not happen now after `backend` was adjusted to `non-triggers` when `empty` payload.

</details>

---

<details close>
<summary>4. 🟩 Duplicate added keys in `livescores_now_scoreboard`</summary>
<br>

> ℹ At times some `player-ids` seems to be duplicated, added a `.TryAdd(..)` method instead.

```
ℹ️ Issue Details

• Method Name: ENDPOINT_livescores_now_scoreboard
• Reason: An item with the same key has already been added. Key: 422
• Stacktrace: at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) at backend_betarena_v2.Services.Data.Football.DataFixtureV3.GenerateFixturePlayerDict(List`1 fixtureList) in /src/Services/Data/Football/Data.Fixture.cs:line 216 at backend_betarena_v2.Services.Entry.Entry_B_G_LN.EntryLivescoresInplayV3Async(Parameters parameters) in /src/Services/Entry/Entry.Livescores.cs:line 192 at backend_betarena_v2.Services.Entry._TEMPLATE.MainEntry_01(Func`2 fn, String methodName, String env, Parameters parameters) in /src/Services/Entry/_TEMPLATE.cs:line 72
```

</details>

---

<details close>
<summary>5. ❗️ PostgreSQL query resize error | Promoted to Issue</summary>
<br>

<img
src="https://github.com/Betarena/scores/assets/20924663/731a1421-ce32-4654-ba38-7d6c5e54e337"
width=350
/>

```
{
    "arguments": [
        "(Oid 23,Just (\"\\SOH\\US{p\",Binary))"
    ],
    "error": {
        "description": null,
        "exec_status": "FatalError",
        "hint": null,
        "message": "could not resize shared memory segment \"/PostgreSQL.1638492616\" to 1048576 bytes: No space left on device",
        "status_code": "53100"
    },
    "prepared": true,
    "statement": "SELECT  coalesce(json_agg(\"root\" ), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_e\"  FROM  (SELECT  \"_root.base\".\"id\" AS \"id\", \"_root.base\".\"alt_links\" AS \"alt_links\", \"_root.base\".\"category\" AS \"category\", \"_root.base\".\"url\" AS \"url\", \"_root.base\".\"created_at\" AS \"created_at\"       ) AS \"_e\"      ) ) AS \"root\" FROM  (SELECT  *  FROM \"public\".\"links_map\"  WHERE (((\"public\".\"links_map\".\"id\") = (($1)::integer)) OR (((\"public\".\"links_map\".\"id\") IS NULL) AND ((($1)::integer) IS NULL)))    LIMIT 50 OFFSET 0) AS \"_root.base\"      ) AS \"_root\"      "
}
```

```
{
    "arguments": [],
    "error": {
        "description": null,
        "exec_status": "FatalError",
        "hint": null,
        "message": "could not resize shared memory segment \"/PostgreSQL.1764714019\" to 2097152 bytes: No space left on device",
        "status_code": "53100"
    },
    "prepared": false,
    "statement": "SELECT\n    COALESCE(Json_agg(Row_to_json(info)), '[]' :: json) AS tables\n  FROM (\n    WITH partitions AS (\n      SELECT array(\n        WITH partitioned_tables AS (SELECT array(SELECT oid FROM pg_class WHERE relkind = 'p') AS parent_tables)\n        SELECT\n        child.relname       AS partition\n    FROM partitioned_tables, pg_inherits\n        JOIN pg_class child             ON pg_inherits.inhrelid   = child.oid\n        JOIN pg_namespace nmsp_child    ON nmsp_child.oid   = child.relnamespace\n    where ((nmsp_child.nspname='public') or (nmsp_child.nspname='language'))\n    AND pg_inherits.inhparent = ANY (partitioned_tables.parent_tables)\n      ) AS names\n    )\n    SELECT\n      pgn.nspname AS table_schema,\n      pgc.relname AS table_name,\n      CASE\n        WHEN pgc.relkind = 'r' THEN 'TABLE'\n        WHEN pgc.relkind = 'f' THEN 'FOREIGN TABLE'\n        WHEN pgc.relkind = 'v' THEN 'VIEW'\n        WHEN pgc.relkind = 'm' THEN 'MATERIALIZED VIEW'\n        WHEN pgc.relkind = 'p' THEN 'PARTITIONED TABLE'\n      END AS table_type,\n      obj_description(pgc.oid) AS comment,\n      COALESCE(json_agg(DISTINCT row_to_json(isc) :: jsonb || jsonb_build_object('comment', col_description(pga.attrelid, pga.attnum))) filter (WHERE isc.column_name IS NOT NULL), '[]' :: json) AS columns,\n      COALESCE(json_agg(DISTINCT row_to_json(ist) :: jsonb || jsonb_build_object('comment', obj_description(pgt.oid))) filter (WHERE ist.trigger_name IS NOT NULL), '[]' :: json) AS triggers,\n      row_to_json(isv) AS view_info\n      FROM partitions, pg_class as pgc\n      INNER JOIN pg_namespace as pgn\n        ON pgc.relnamespace = pgn.oid\n    /* columns */\n    /* This is a simplified version of how information_schema.columns was\n    ** implemented in postgres 9.5, but modified to support materialized\n    ** views.\n    */\n    LEFT OUTER JOIN pg_attribute AS pga\n      ON pga.attrelid = pgc.oid\n    LEFT OUTER JOIN (\n      SELECT\n        nc.nspname         AS table_schema,\n        c.relname          AS table_name,\n        a.attname          AS column_name,\n        a.attnum           AS ordinal_position,\n        pg_get_expr(ad.adbin, ad.adrelid) AS column_default,\n        CASE WHEN a.attnotnull OR (t.typtype = 'd' AND t.typnotnull) THEN 'NO' ELSE 'YES' END AS is_nullable,\n        CASE WHEN t.typtype = 'd' THEN\n          CASE WHEN bt.typelem <> 0 AND bt.typlen = -1 THEN 'ARRAY'\n               WHEN nbt.nspname = 'pg_catalog' THEN format_type(t.typbasetype, null)\n               ELSE 'USER-DEFINED' END\n        ELSE\n          CASE WHEN t.typelem <> 0 AND t.typlen = -1 THEN 'ARRAY'\n               WHEN nt.nspname = 'pg_catalog' THEN format_type(a.atttypid, null)\n               ELSE 'USER-DEFINED' END\n        END AS data_type,\n        coalesce(bt.typname, t.typname) AS data_type_name\n      FROM (pg_attribute a LEFT JOIN pg_attrdef ad ON attrelid = adrelid AND attnum = adnum)\n        JOIN (pg_class c JOIN pg_namespace nc ON (c.relnamespace = nc.oid)) ON a.attrelid = c.oid\n        JOIN (pg_type t JOIN pg_namespace nt ON (t.typnamespace = nt.oid)) ON a.atttypid = t.oid\n        LEFT JOIN (pg_type bt JOIN pg_namespace nbt ON (bt.typnamespace = nbt.oid))\n          ON (t.typtype = 'd' AND t.typbasetype = bt.oid)\n        LEFT JOIN (pg_collation co JOIN pg_namespace nco ON (co.collnamespace = nco.oid))\n          ON a.attcollation = co.oid AND (nco.nspname, co.collname) <> ('pg_catalog', 'default')\n      WHERE (NOT pg_is_other_temp_schema(nc.oid))\n        AND a.attnum > 0 AND NOT a.attisdropped AND c.relkind in ('r', 'v', 'm', 'f', 'p')\n        AND (pg_has_role(c.relowner, 'USAGE')\n             OR has_column_privilege(c.oid, a.attnum,\n                                     'SELECT, INSERT, UPDATE, REFERENCES'))\n    ) AS isc\n      ON  isc.table_schema = pgn.nspname\n      AND isc.table_name   = pgc.relname\n      AND isc.column_name  = pga.attname\n    /* triggers */\n    LEFT OUTER JOIN pg_trigger AS pgt\n      ON pgt.tgrelid = pgc.oid\n    LEFT OUTER JOIN information_schema.triggers AS ist\n      ON  ist.event_object_schema = pgn.nspname\n      AND ist.event_object_table  = pgc.relname\n      AND ist.trigger_name        = pgt.tgname\n    /* This is a simplified version of how information_schema.views was\n    ** implemented in postgres 9.5, but modified to support materialized\n    ** views.\n    */\n    LEFT OUTER JOIN (\n      SELECT\n        nc.nspname         AS table_schema,\n        c.relname          AS table_name,\n        CASE WHEN pg_has_role(c.relowner, 'USAGE') THEN pg_get_viewdef(c.oid) ELSE null END AS view_definition,\n        CASE WHEN pg_relation_is_updatable(c.oid, false) & 20 = 20 THEN 'YES' ELSE 'NO' END AS is_updatable,\n        CASE WHEN pg_relation_is_updatable(c.oid, false) &  8 =  8 THEN 'YES' ELSE 'NO' END AS is_insertable_into,\n        CASE WHEN EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = c.oid AND tgtype & 81 = 81) THEN 'YES' ELSE 'NO' END AS is_trigger_updatable,\n        CASE WHEN EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = c.oid AND tgtype & 73 = 73) THEN 'YES' ELSE 'NO' END AS is_trigger_deletable,\n        CASE WHEN EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = c.oid AND tgtype & 69 = 69) THEN 'YES' ELSE 'NO' END AS is_trigger_insertable_into\n      FROM pg_namespace nc, pg_class c\n      WHERE c.relnamespace = nc.oid\n        AND c.relkind in ('v', 'm')\n        AND (NOT pg_is_other_temp_schema(nc.oid))\n        AND (pg_has_role(c.relowner, 'USAGE')\n             OR has_table_privilege(c.oid, 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER')\n             OR has_any_column_privilege(c.oid, 'SELECT, INSERT, UPDATE, REFERENCES'))\n    ) AS isv\n      ON  isv.table_schema = pgn.nspname\n      AND isv.table_name   = pgc.relname\n    WHERE\n      pgc.relkind IN ('r', 'v', 'f', 'm', 'p')\n      and ((pgn.nspname='public') or (pgn.nspname='language'))\n    GROUP BY pgc.oid, pgn.nspname, pgc.relname, table_type, isv.*\n  ) AS info;"
}
```

</details>

**Comment by jonsnowpt** [comment]
@migbash 

What is the goal in this request?

**Comment by migbash** [comment]
> @jonsnowpt To keep track of issues that are identified across the `platform` , such as: `links` and so forth, which can then be escalated into their own `issue` cards.
