### ISSUE TITLE
[Bug]: Competitions are not updating their status 

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#1761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐞 Describe the bug

The competitions are not updating their status.

Neither the fixtures nor competition status has changed.

![Screenshot 2023-10-17 at 12 11 05](https://github.com/Betarena/scores/assets/37311649/9ee61501-9eee-456a-8129-aa126f2220d5)
![Screenshot 2023-10-17 at 12 11 11](https://github.com/Betarena/scores/assets/37311649/9b06909e-9031-468c-8685-23521146ec7b)

### 🤔 Expected Behavior

Competition and fixture status correctly change.

### What environment is the bug/issue detected in.

- [X] Production (scores.betarena.com)
- [ ] Development

### What browsers are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Brave
- [ ] Opera

### What device/platform can the problem be seen?

- [ ] 📱 Mobile
- [ ] 💻 Tablet
- [X] 🖥️ Laptop/Desktop

### Steps To Reproduce

https://scores.betarena.com/competitions/predictor/team-luxembourg-will-win/172
https://scores.betarena.com/competitions/predictor/team-honduras-will-win/173

**Comment by migbash** [comment]
> **Note**
> This is `controlled` by the `livescores/now` endpoint trigger by `Sportmonks V2`.
> Upon preliminary inspection, the following logs can be observed since yesterday:

```bash
10/15/2023 19:02:01 | Process: ENDPOINT_5s_livescore_now_update | OPTIONS:◈ env: prod
❌ Error :: Object reference not set to an instance of an object.
❌ Stacktrace ::    at backend_betarena_v2.Services.Data.Football.Historic_Fixture.FixtureStatusFT(List`1 dataList) in /src/Services/Data/Football/Data.HistoricFixture.cs:line 830
   at backend_betarena_v2.Services.Entry.Entry_B_HF.Entry_B_HF_1_Async(Parameters parameters) in /src/Services/Entry/Entry.HistoricFix.cs:line 358
   at backend_betarena_v2.Services.Entry.Entry_B_G_LN.SubTask_01_Async(Parameters parameters, List`1 livescoreList, Dictionary`2 liveFixturesStatusDict) in /src/Services/Entry/Entry.Livescores.cs:line 261
   at backend_betarena_v2.Services.Entry.Entry_B_G_LN.Entry_B_G_LN_M_Async(Parameters parameters) in /src/Services/Entry/Entry.Livescores.cs:line 95
   at backend_betarena_v2.Services.Entry._TEMPLATE.MainEntry_01_Async(Func`2 fn, String methodName, String env, Parameters parameters) in /src/Services/Entry/_TEMPLATE.cs:line 122
[...]
10/17/2023 11:07:01 | Process: ENDPOINT_livescores_now_scoreboard | OPTIONS:◈ env: prod
❌ Error :: Object reference not set to an instance of an object.
❌ Stacktrace ::    at backend_betarena_v2.Services.Data.Football.Historic_Fixture.FixtureStatusFT(List`1 dataList) in /src/Services/Data/Football/Data.HistoricFixture.cs:line 830
   at backend_betarena_v2.Services.Entry.Entry_B_HF.Entry_B_HF_1_Async(Parameters parameters) in /src/Services/Entry/Entry.HistoricFix.cs:line 358
   at backend_betarena_v2.Services.Entry.Entry_B_G_LN.SubTask_01_Async(Parameters parameters, List`1 livescoreList, Dictionary`2 liveFixturesStatusDict) in /src/Services/Entry/Entry.Livescores.cs:line 261
   at backend_betarena_v2.Services.Entry.Entry_B_G_LN.Entry_B_G_LN_M_Async(Parameters parameters) in /src/Services/Entry/Entry.Livescores.cs:line 95
   at backend_betarena_v2.Services.Entry._TEMPLATE.MainEntry_01_Async(Func`2 fn, String methodName, String env, Parameters parameters) in /src/Services/Entry/_TEMPLATE.cs:line 122
```

with a complementary error registered similarly prior to that of the `FixtureStatusFT(..)` being: 

```bash
❌ Error :: Object reference not set to an instance of an object.
❌ Stacktrace ::    at backend_betarena_v2.Services.Sportmonk.SportmonkFixtures.FixturesDateRange_Async(String startDate, String endDate, String type, String env, String leagueIds, String seasonIds) in /src/Services/Sportmonk/Sportmonk.Fixtures.cs:line 154
   at backend_betarena_v2.Services.Entry.Entry_B_HF.Entry_B_HF_0_Async(Parameters parameters) in /src/Services/Entry/Entry.HistoricFix.cs:line 179
   at backend_betarena_v2.Services.Entry.Entry_B_SFL.SubTask_02_Async(Parameters parameters, List`1 currentSeasonDataList, List`1 newLeagueDataList) in /src/Services/Entry/Entry.Leagues.cs:line 371
   at backend_betarena_v2.Services.Entry.Entry_B_SFL.Entry_B_SFL_A_1_Async(Parameters parameters) in /src/Services/Entry/Entry.Leagues.cs:line 181
   at backend_betarena_v2.Services.Entry._TEMPLATE.MainEntry_01_Async(Func`2 fn, String methodName, String env, Parameters parameters) in /src/Services/Entry/_TEMPLATE.cs:line 122
```
